/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author mneura
 */
public class AdminDashboard extends javax.swing.JFrame {

    private DashboardPanel dashboardPanel = null;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        init();
    }

    private void init() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        brandPanel.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        brandPanel.setBackground(new Color(255, 255, 255, 25));
        sidebarPanel.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        sidebarPanel.setBackground(new Color(255, 255, 255, 25));
        topHeaderPanel.putClientProperty(FlatClientProperties.STYLE, "arc:10");
        topHeaderPanel.setBackground(new Color(255, 255, 255, 25));
        container.putClientProperty(FlatClientProperties.STYLE, "arc:10");

        dashboardBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        dashboardBTN.setFocusPainted(false);
        flightScheduleBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        flightScheduleBTN.setFocusPainted(false);
        editFlightBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        editFlightBTN.setFocusPainted(false);
        assignAircraftBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        assignAircraftBTN.setFocusPainted(false);
        assignGateBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        assignGateBTN.setFocusPainted(false);
        manageUsersBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        manageUsersBTN.setFocusPainted(false);
        logOutBTN.setBorder(BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 2));
        logOutBTN.setFocusPainted(false);

        container.setLayout(new CardLayout());
        loadDashboard();
    }

    private void loadDashboard() {
        dashboardPanel = new DashboardPanel(); // create once
        switchPanel(dashboardPanel, "dashboard");
    }

    private void switchPanel(JPanel panel, String name) {
        if (container.getComponentZOrder(panel) == -1) {
            container.add(panel, name);
        }
        CardLayout cl = (CardLayout) container.getLayout();
        cl.show(container, name);
        refreshUI();
    }

    private void refreshUI() {
        container.revalidate();
        container.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePanel = new javax.swing.JPanel();
        brandPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        dashboardBTN = new javax.swing.JButton();
        flightScheduleBTN = new javax.swing.JButton();
        assignAircraftBTN = new javax.swing.JButton();
        editFlightBTN = new javax.swing.JButton();
        manageUsersBTN = new javax.swing.JButton();
        assignGateBTN = new javax.swing.JButton();
        logOutBTN = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        topHeaderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AeroDesk - Admininstrator dashboard");
        setResizable(false);

        framePanel.setBackground(new java.awt.Color(0, 0, 0));

        brandPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AeroDeskIcon.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AeroDesk Pro");

        javax.swing.GroupLayout brandPanelLayout = new javax.swing.GroupLayout(brandPanel);
        brandPanel.setLayout(brandPanelLayout);
        brandPanelLayout.setHorizontalGroup(
            brandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        brandPanelLayout.setVerticalGroup(
            brandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 0));

        dashboardBTN.setBackground(new java.awt.Color(102, 0, 255));
        dashboardBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        dashboardBTN.setText("Dashboard");
        dashboardBTN.setToolTipText("Dashboard");
        dashboardBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBTNActionPerformed(evt);
            }
        });

        flightScheduleBTN.setBackground(new java.awt.Color(102, 0, 255));
        flightScheduleBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/schedule.png"))); // NOI18N
        flightScheduleBTN.setText("Flight Schedule");
        flightScheduleBTN.setToolTipText("Flight Schedule");
        flightScheduleBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        flightScheduleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightScheduleBTNActionPerformed(evt);
            }
        });

        assignAircraftBTN.setBackground(new java.awt.Color(102, 0, 255));
        assignAircraftBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flight.png"))); // NOI18N
        assignAircraftBTN.setText("Assign Aircraft");
        assignAircraftBTN.setToolTipText("Assign Aircraft");
        assignAircraftBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        assignAircraftBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignAircraftBTNActionPerformed(evt);
            }
        });

        editFlightBTN.setBackground(new java.awt.Color(102, 0, 255));
        editFlightBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        editFlightBTN.setText("Edit Flight Details");
        editFlightBTN.setToolTipText("Edit Flight Details");
        editFlightBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        manageUsersBTN.setBackground(new java.awt.Color(102, 0, 255));
        manageUsersBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        manageUsersBTN.setText("Manage Users");
        manageUsersBTN.setToolTipText("Manage User");
        manageUsersBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageUsersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersBTNActionPerformed(evt);
            }
        });

        assignGateBTN.setBackground(new java.awt.Color(102, 0, 255));
        assignGateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gate.png"))); // NOI18N
        assignGateBTN.setText("Assign Gate");
        assignGateBTN.setToolTipText("Assign Gate");
        assignGateBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        logOutBTN.setBackground(new java.awt.Color(102, 0, 255));
        logOutBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        logOutBTN.setText("LogOut");
        logOutBTN.setToolTipText("LogOut");
        logOutBTN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flightScheduleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editFlightBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(assignAircraftBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assignGateBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUsersBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dashboardBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(flightScheduleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editFlightBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(assignAircraftBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(assignGateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageUsersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        container.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        topHeaderPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bell.png"))); // NOI18N
        jLabel3.setToolTipText("Notifications");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administrator Dashboard");

        javax.swing.GroupLayout topHeaderPanelLayout = new javax.swing.GroupLayout(topHeaderPanel);
        topHeaderPanel.setLayout(topHeaderPanelLayout);
        topHeaderPanelLayout.setHorizontalGroup(
            topHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topHeaderPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );
        topHeaderPanelLayout.setVerticalGroup(
            topHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(topHeaderPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout framePanelLayout = new javax.swing.GroupLayout(framePanel);
        framePanel.setLayout(framePanelLayout);
        framePanelLayout.setHorizontalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(brandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        framePanelLayout.setVerticalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(brandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void flightScheduleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightScheduleBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightScheduleBTNActionPerformed

    private void assignAircraftBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignAircraftBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignAircraftBTNActionPerformed

    private void manageUsersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUsersBTNActionPerformed

    private void logOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBTNActionPerformed

    private void dashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBTNActionPerformed
        // TODO add your handling code here:
        if (dashboardPanel == null) {
            dashboardPanel = new DashboardPanel();
        }
        switchPanel(dashboardPanel, "dashboard");
    }//GEN-LAST:event_dashboardBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignAircraftBTN;
    private javax.swing.JButton assignGateBTN;
    private javax.swing.JPanel brandPanel;
    private javax.swing.JPanel container;
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JButton editFlightBTN;
    private javax.swing.JButton flightScheduleBTN;
    private javax.swing.JPanel framePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logOutBTN;
    private javax.swing.JButton manageUsersBTN;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel topHeaderPanel;
    // End of variables declaration//GEN-END:variables
}
