/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
/**
 *
 * @author mneura
 */
public class Redirector extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public Redirector() {
        initComponents();
        adminLoginBTN.putClientProperty(FlatClientProperties.STYLE, "arc:15");
        staffLoginBTN.putClientProperty(FlatClientProperties.STYLE, "arc:15");
        userLoginBTN.putClientProperty(FlatClientProperties.STYLE, "arc:15");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminLoginBTN = new javax.swing.JButton();
        staffLoginBTN = new javax.swing.JButton();
        userLoginBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AeroDesk - Welcome");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminLoginBTN.setBackground(new java.awt.Color(0, 0, 0));
        adminLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        adminLoginBTN.setText("Administrator");
        adminLoginBTN.setBorder(null);
        adminLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(adminLoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 47));

        staffLoginBTN.setBackground(new java.awt.Color(0, 0, 0));
        staffLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        staffLoginBTN.setText("Staff Officer");
        staffLoginBTN.setBorder(null);
        staffLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLoginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(staffLoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 120, 47));

        userLoginBTN.setBackground(new java.awt.Color(0, 0, 0));
        userLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        userLoginBTN.setText("User");
        userLoginBTN.setBorder(null);
        userLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(userLoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 120, 47));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to AeroDesk Pro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BackgroundBanner.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdministratorLogin().setVisible(true);
    }//GEN-LAST:event_adminLoginBTNActionPerformed

    private void staffLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffLoginBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StaffLogin().setVisible(true);
    }//GEN-LAST:event_staffLoginBTNActionPerformed

    private void userLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserLogin().setVisible(true);
    }//GEN-LAST:event_userLoginBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Redirector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginBTN;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton staffLoginBTN;
    private javax.swing.JButton userLoginBTN;
    // End of variables declaration//GEN-END:variables
}
