/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;


/**
 *
 * @author mneura
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public ReportPanel() {
        initComponents();
        init();
    }

    private void init() {
        jTabbedPane1.setBackground(new Color(255, 255, 255, 25));
        aircraftDetails.setBackground(new Color(255, 255, 255, 25));
        airticketInvoices.setBackground(new Color(255, 255, 255, 25));
        incomeOverview.setBackground(new Color(255, 255, 255, 25));
        reservationHistory.setBackground(new Color(255, 255, 255, 25));
        routeHistory.setBackground(new Color(255, 255, 255, 25));
        staffDetails.setBackground(new Color(255, 255, 255, 25));
        systemLogs.setBackground(new Color(255, 255, 255, 25));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        incomeOverview = new javax.swing.JPanel();
        reservationHistory = new javax.swing.JPanel();
        routeHistory = new javax.swing.JPanel();
        staffDetails = new javax.swing.JPanel();
        aircraftDetails = new javax.swing.JPanel();
        airticketInvoices = new javax.swing.JPanel();
        systemLogs = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        incomeOverview.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout incomeOverviewLayout = new javax.swing.GroupLayout(incomeOverview);
        incomeOverview.setLayout(incomeOverviewLayout);
        incomeOverviewLayout.setHorizontalGroup(
            incomeOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        incomeOverviewLayout.setVerticalGroup(
            incomeOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Income Overview", incomeOverview);

        reservationHistory.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout reservationHistoryLayout = new javax.swing.GroupLayout(reservationHistory);
        reservationHistory.setLayout(reservationHistoryLayout);
        reservationHistoryLayout.setHorizontalGroup(
            reservationHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        reservationHistoryLayout.setVerticalGroup(
            reservationHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reservation History", reservationHistory);

        routeHistory.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout routeHistoryLayout = new javax.swing.GroupLayout(routeHistory);
        routeHistory.setLayout(routeHistoryLayout);
        routeHistoryLayout.setHorizontalGroup(
            routeHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        routeHistoryLayout.setVerticalGroup(
            routeHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Route History", routeHistory);

        staffDetails.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout staffDetailsLayout = new javax.swing.GroupLayout(staffDetails);
        staffDetails.setLayout(staffDetailsLayout);
        staffDetailsLayout.setHorizontalGroup(
            staffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        staffDetailsLayout.setVerticalGroup(
            staffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Staff Details", staffDetails);

        aircraftDetails.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout aircraftDetailsLayout = new javax.swing.GroupLayout(aircraftDetails);
        aircraftDetails.setLayout(aircraftDetailsLayout);
        aircraftDetailsLayout.setHorizontalGroup(
            aircraftDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        aircraftDetailsLayout.setVerticalGroup(
            aircraftDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Aircraft Details", aircraftDetails);

        airticketInvoices.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout airticketInvoicesLayout = new javax.swing.GroupLayout(airticketInvoices);
        airticketInvoices.setLayout(airticketInvoicesLayout);
        airticketInvoicesLayout.setHorizontalGroup(
            airticketInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        airticketInvoicesLayout.setVerticalGroup(
            airticketInvoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Airticket Invoices", airticketInvoices);

        systemLogs.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout systemLogsLayout = new javax.swing.GroupLayout(systemLogs);
        systemLogs.setLayout(systemLogsLayout);
        systemLogsLayout.setHorizontalGroup(
            systemLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        systemLogsLayout.setVerticalGroup(
            systemLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("System logs", systemLogs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aircraftDetails;
    private javax.swing.JPanel airticketInvoices;
    private javax.swing.JPanel incomeOverview;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel reservationHistory;
    private javax.swing.JPanel routeHistory;
    private javax.swing.JPanel staffDetails;
    private javax.swing.JPanel systemLogs;
    // End of variables declaration//GEN-END:variables
}
